---
title: "quick_plots"
format: html
editor: visual
---

```{r}
#| include: false
library(tidyverse)
library(readxl)
```

```{r}
# Function for reading QAQC files
read_qaqc <- function(file_path) {
  # Read Final_Import_Site sheet
  qaqc <- readxl::read_xlsx(file_path, sheet = "Final_Import_Site#") |>
     # Datetime correction when converting from decimal
    dplyr::mutate(dtime = `Standard Dtime` + lubridate::seconds(1),
                  dtime = lubridate::floor_date(dtime, "minute")) |>
    dplyr::select(dtime,  `Corrected Water Depth (ft)`) |>
    dplyr::rename(cwlevel = `Corrected Water Depth (ft)`)
}

# Function for estimating storage volume from storm
storage_vol <- function(contrib_imp_area, max_storm_depth) {
  vol <- contrib_imp_area*(max_storm_depth/12)
}
```

## Import QAQC

```{r}
# Read OW2 Q1 QAQC file
ow2_level_q1_corrected <- read_qaqc("data/1140-3-2/OW2/1140-3-2_OW2_25Q1_15min_QAQC_20250710_KR.xlsx")

# Read OW2 Q2 QAQC file
ow2_level_q2_corrected <- read_qaqc("data/1140-3-2/OW2/1140-3-2_OW2_25Q2_15min_QAQC_20250710_KR.xlsx")

# Read OW1 Q1 QAQC file
ow1_level_q1_corrected <- read_qaqc("data/1140-3-2/OW1/1140-3-2_OW1_25Q1_15min_QAQC_20250710_KR.xlsx")

# Read OW2 Q2 QAQC file
ow1_level_q2_corrected <- read_qaqc("data/1140-3-2/OW1/1140-3-2_OW1_25Q2_15min_QAQC_20250710_KR.xlsx")

# Read and combine rain data for both quarters
rain_q1 <- read_xlsx("data/1140-3-2/OW2/1140-3-2_OW2_25Q1_15min_QAQC_20250710_KR.xlsx",
             sheet = "Rainfall Data")

rain_q2 <- read_xlsx("data/1140-3-2/OW2/1140-3-2_OW2_25Q2_15min_QAQC_20250710_KR.xlsx",
             sheet = "Rainfall Data")

rain <- rbind(rain_q1, rain_q2) |>
  rename(dtime = `DateTime`,
         rainfall = `Rainfall (in.)`,
         gauge_uid = `Rain Gauge #`,
         rain_event_uid = `Rainfall Event ID`) 

```

```{r}
# Adjust for distance between bedding and crate
ow1_level_q2_corrected <- ow1_level_q2_corrected |>
  mutate(ow1_cwlevel = cwlevel + 0.25) |> select(-cwlevel)

ow1_level_q1_corrected <- ow1_level_q1_corrected |>
  mutate(ow1_cwlevel = cwlevel + 0.25) |> select(-cwlevel)

ow2_level_q1_corrected <- ow2_level_q1_corrected |>
  mutate(ow2_cwlevel = cwlevel+0.25) |> select(-cwlevel)

ow2_level_q2_corrected <- ow2_level_q2_corrected |>
  mutate(ow2_cwlevel = cwlevel + 0.25) |> select(-cwlevel)

# Combine each OW data into one df
ow1_comb <- rbind(ow1_level_q1_corrected, ow1_level_q2_corrected)

ow2_comb <- rbind(ow2_level_q1_corrected, ow2_level_q2_corrected)

# Combine level and rain dfs
ow_comb <- ow1_comb |>
  # Combine with ow2
  left_join(ow2_comb, join_by(dtime == dtime)) |>
  # Comvibine with rain data
  left_join(rain, join_by(dtime == dtime)) |>
  mutate(rainfall = if_else(is.na(rainfall), 0, rainfall))
```

### Estimating Volume from Storm Pre-Maintenance

-   Contributing Impervious Area = 88619

-   Storage Volume = 9545

Storm size required to fill up the system:

$$
\begin{align} 
\text{Storage Volume} &= \text{ Contributing Imp. Area} \cdot \frac{\text{Max Storm Depth}}{
\text{12 in/ft}} \\ \\ 
\text{Max Storm Depth} &= \frac{12 \text{ in/ft} \cdot \text{Storage Volume}}{\text{Contributing Imp. Area}} \\ \\ 
\text{Max Storm Depth} &= \frac{12 \text{ in/ft} \cdot 9545}{88619} \\ \\ 
\text{Max Storm Depth} &= 1.293 \approx \text{1.29"}
\end{align}
$$

Therefore, to calculate the volume with a 0.67" storm:

$$
\begin{align}
\text{Storage Volume } &= 88619 \cdot \frac{0.67}{12 \text{ in/ft}} \\ \\ 
\text{Storage Volume } &= 4947 \text{ft}^3 \\ \\
\text{\% of Volume } &= \frac{4947}{9545} \approx 52\text{\%}
\end{align}
$$

```{r}
# OW2 plot before maintenance
ow_preevent <- ggplot(ow_comb |> 
                      dplyr::filter(
                        between(dtime, 
                                ymd_hms("2025-04-26 6:00:00"),
                                ymd_hms("2025-04-29 6:00:00")
                                )),
                      aes(x = dtime)) +
  # Storage volume for OW2
  geom_ribbon(aes(ymin = 0, ymax = 3.17), fill = "lightblue", alpha = 0.4) +
  # Storage volume for OW1
  # geom_ribbon(aes(ymin = 0, ymax = 3.42), fill = "lightblue", alpha = 0.4) +
  # # Water level line plots
  geom_line(aes(y = ow1_cwlevel, color = "OW1 Water Level"),
            linewidth = 1.1) +
  geom_line(aes(color = "OW2 Water Level", y = ow2_cwlevel),
            linewidth = 1.1) +
  # Bottom of crate elevation
  geom_hline(aes(yintercept = 0.25),
             linewidth = 0.6,
           linetype = "dashed")  +
  # geom_label(x =  ymd_hms("2025-04-26 06:00:00"),
  #          y = .91, 
  #          aes(label = "Bottom of Crate",
  #          hjust = 0,
  #          fill = "lightblue",
  #          default.color = "lightblue"
  #          )) +
  # annotate("curve",
  #          x = ymd_hms("2025-04-26 06:00:00"),
  #          y = 0.75,
  #          yend = 0.25,
  #          xend = ymd_hms("2025-04-26 05:00:00"),
  #          curvature = 0.3,
  #          linewidth = 0.7,
  #          arrow = arrow(length = unit(1.5, "mm"))) +
  annotate("text",
           x = ymd_hms("2025-04-26 06:15:00"),
           y = .8,
           label = "Bottom of Crate",
           hjust = 0) +
  # Bottom of Stone Storage elevation
  geom_hline(yintercept = 0.0) +
  annotate("text", x =  ymd_hms("2025-04-26 06:00:00"),
           y = -0.1, 
           label = "Bottom of Stone Storage",
           hjust = 0) +
  # Top of storage elevation (OW2)
  geom_hline(yintercept = 3.17, linetype = "dashed") +
    annotate("text",
             x =  ymd_hms("2025-04-26 06:00:00"),
             y = 3.37,
             label = "Top of Stone Storage",
             hjust = 0) +
  # # Top of storage elevation (OW1)
  #   geom_hline(yintercept = 3.42, linetype = "dashed") +
  #   annotate("text",
  #            x =  ymd_hms("2025-04-26 06:00:00"),
  #            y = 3.62, 
  #            label = "Top of Stone Storage (OW1)",
  #            hjust = 0) +
  # Expected response elevation
    geom_hline(yintercept = 1.65, linetype = "dashed") +
    annotate("text",
             x =  ymd_hms("2025-04-28 06:00:00"),
             y = 1.85, 
             label = "Expected Max Response to Storm Event",
             hjust = 0) +
  # Zoom for water level plot
  coord_cartesian(ylim = c(-0.5, 4)) +
  labs(
    title = "1140-3-2 Water Level Response from 2025-04-26 Storm",
    x = "Date",
    y = "Water level (ft)",
    color = NULL
  )  +
  theme(legend.position = "bottom") +
  # Colors for water levels
   scale_color_manual(values = c(
    "OW1 Water Level" = "cornflowerblue",
    "OW2 Water Level" = "#2a3782")) +
  # Match y-axis formatting to rain plot
  scale_y_continuous(labels = function(x) sprintf("%.2f", x))
  
# Rain plot
rainfall_pre <- ggplot(ow_comb |> 
                      dplyr::filter(
                        between(dtime, 
                                ymd_hms("2025-04-26 06:00:00"),
                                ymd_hms("2025-04-29 06:00:00")
                                )),
                   aes(y = rainfall)) +
  geom_col(aes(dtime)) + 
  scale_y_continuous(lim = c(0, 1)) +
  labs(
    x = NULL,
    y = "Rainfall (in)",
    title = "1140-3-2 Rainfall from 2025-04-26 Storm (Total: 0.67\")"
  )

# Combine plots
cowplot::plot_grid(rainfall_pre, ow_preevent,
                   nrow = 2,
                   rel_heights = c(1,3),
                   rel_widths = c(1,1)
                   )
  
```

### Calculating the Percent of Storage Volume

$$
\begin{align}
\text{Storage Volume } &= 88619 \cdot \frac{0.64}{12 \text{ in/ft}} \\ \\ 
\text{Storage Volume } &= 4726 \text{ft}^3 \\ \\
\text{\% of Volume } &= \frac{4726}{9545} \approx 50\text{\%}
\end{align}
$$

```{r}
# OW2 plot after maintenance
ow_postevent <- ggplot(ow_comb |> 
                      dplyr::filter(
                        between(dtime, 
                                ymd_hms("2025-06-14 6:00:00"),
                                ymd_hms("2025-06-18 6:00:00")
                                )),
                      aes(x = dtime)) + 
   geom_ribbon(aes(ymin = 0, ymax = 3.17), fill = "lightblue", alpha = 0.4) +
  # Storage volume for OW1
  # geom_ribbon(aes(ymin = 0, ymax = 3.42), fill = "lightblue", alpha = 0.4) +
  # # Water level line plots
  geom_line(aes(y = ow1_cwlevel, color = "OW1 Water Level"),
            linewidth = 1.1) +
  geom_line(aes(color = "OW2 Water Level", y = ow2_cwlevel),
            linewidth = 1.1) +
  # Bottom of crate elevation
  geom_hline(aes(yintercept = 0.25),
             linewidth = 0.6,
           linetype = "dashed")  +
  # geom_label(x =  ymd_hms("2025-04-26 06:00:00"),
  #          y = .91, 
  #          aes(label = "Bottom of Crate",
  #          hjust = 0,
  #          fill = "lightblue",
  #          default.color = "lightblue"
  #          )) +
  # annotate("curve",
  #          x = ymd_hms("2025-04-26 06:00:00"),
  #          y = 0.75,
  #          yend = 0.25,
  #          xend = ymd_hms("2025-04-26 05:00:00"),
  #          curvature = 0.3,
  #          linewidth = 0.7,
  #          arrow = arrow(length = unit(1.5, "mm"))) +
  annotate("text",
           x = ymd_hms("2025-06-14 06:15:00"),
           y = .8,
           label = "Bottom of Crate",
           hjust = 0) +
  # Bottom of Stone Storage elevation
  geom_hline(yintercept = 0.0) +
  annotate("text", x =  ymd_hms("2025-06-14 06:00:00"),
           y = -0.1, 
           label = "Bottom of Stone Storage",
           hjust = 0) +
  # Top of storage elevation (OW2)
  geom_hline(yintercept = 3.17, linetype = "dashed") +
    annotate("text",
             x =  ymd_hms("2025-06-14 06:00:00"),
             y = 3.37,
             label = "Top of Stone Storage",
             hjust = 0) +
  # # Top of storage elevation (OW1)
  #   geom_hline(yintercept = 3.42, linetype = "dashed") +
  #   annotate("text",
  #            x =  ymd_hms("2025-04-26 06:00:00"),
  #            y = 3.62, 
  #            label = "Top of Stone Storage (OW1)",
  #            hjust = 0) +
  # Expected response elevation
    geom_hline(yintercept = 1.65, linetype = "dashed") +
    annotate("text",
             x =  ymd_hms("2025-06-17 00:00:00"),
             y = 1.85, 
             label = "Expected Max Response to Storm Event",
             hjust = 0) +
  # Zoom for water level plot
  coord_cartesian(ylim = c(-0.5, 4)) +
  labs(
    title = "1140-3-2 Water Level Response from 2025-06-14 Storm",
    x = "Date",
    y = "Water level (ft)",
    color = NULL
  )  +
  theme(legend.position = "bottom") +
  # Colors for water levels
   scale_color_manual(values = c(
    "OW1 Water Level" = "cornflowerblue",
    "OW2 Water Level" = "#2a3782")) +
  # Match y-axis formatting to rain plot
  scale_y_continuous(labels = function(x) sprintf("%.2f", x))
  
# Rain plot
rainfall_pre <- ggplot(ow_comb |> 
                      dplyr::filter(
                        between(dtime, 
                                ymd_hms("2025-06-14 06:00:00"),
                                ymd_hms("2025-06-18 06:00:00")
                                )),
                   aes(y = rainfall)) +
  geom_col(aes(dtime)) + 
  scale_y_continuous(lim = c(0, 1)) +
  labs(
    x = NULL,
    y = "Rainfall (in)",
    title = "1140-3-2 Rainfall from 2025-06-14 Storm (Total: 0.64\")"
  )
```

```{r}
cowplot::plot_grid(rainfall_post, ow_postevent,
                   nrow = 2,
                   rel_heights = c(1,3),
                   rel_widths = c(1,1)
                   )
```
