---
title: "quick_plots"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readxl)
```

## Import QAQC

```{r}
ow1_level <- read_xlsx("data/1140-3-2/OW1/1140-3-2_OW1_25Q1_15min_QAQC_20250710_KR.xlsx",
             sheet = "Final_Import_Site#")
ow1_level_corrected <- ow1_level |>
  mutate(dtime = `Standard Dtime` + lubridate::seconds(1),
         dtime = floor_date(dtime, "minute")) |>
  select(dtime,  `Corrected Water Depth (ft)`) |>
  rename(cwlevel = `Corrected Water Depth (ft)`)

rain <- read_xlsx("data/1140-3-2/OW1/1140-3-2_OW1_25Q1_15min_QAQC_20250710_KR.xlsx",
             sheet = "Rainfall Data")

ow1_level_2 <- read_xlsx("data/1140-3-2/OW1/1140-3-2_OW1_25Q2_15min_QAQC_20250710_KR.xlsx",
             sheet = "Final_Import_Site#")
ow1_level_2_corrected <- ow1_level |>
  mutate(dtime = `Standard Dtime` + lubridate::seconds(1),
         dtime = floor_date(dtime, "minute")) |>
  select(dtime,  `Corrected Water Depth (ft)`) |>
  rename(cwlevel = `Corrected Water Depth (ft)`)

rain <- read_xlsx("data/1140-3-2/OW1/1140-3-2_OW1_25Q1_15min_QAQC_20250710_KR.xlsx",
             sheet = "Rainfall Data")

rain2 <- read_xlsx("data/1140-3-2/OW1/1140-3-2_OW1_25Q2_15min_QAQC_20250710_KR.xlsx",
             sheet = "Rainfall Data")

rain <- 
  rain |> 
  rename(dtime = `DateTime`,
         rainfall = `Rainfall (in.)`,
         gauge_uid = `Rain Gauge #`,
         rain_event_uid = `Rainfall Event ID`)

rain2 <- 
  rain2 |> 
  rename(dtime = `DateTime`,
         rainfall = `Rainfall (in.)`,
         gauge_uid = `Rain Gauge #`,
         rain_event_uid = `Rainfall Event ID`)
```

```{r}
ow_lvlr <- ow1_level_corrected |>
  mutate(cwlevel = (cwlevel + 1.08)) |>
  left_join(rain, join_by(dtime == dtime)) |>
  na.omit()

ow_lvlr2 <- ow1_level_2_corrected |>
  mutate(cwlevel = (cwlevel + 1.08)) |>
  left_join(rain2, join_by(dtime == dtime)) |>
  na.omit()

ow1_comb <- rbind(ow_lvlr, ow_lvlr2)
```

```{r}
ggplot(ow1_comb, aes(x = dtime, y = cwlevel)) +
  #geom_col(aes(x = dtime, y = rainfall), color = "navy") +
  geom_line(aes(y = cwlevel, )) +
  geom_hline(aes(yintercept = 1.08), color = "red") +
  geom_hline(yintercept = 5.83, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_cartesian(ylim = c(0, 6)) + 
  geom_vline(xintercept = ymd_hms("2025-05-16 12:00:00"))
  
 # scale_y_continuous(sec.axis = sec_axis(~ (.-2)/5, name = "Rainfall (in)"), expand = c(0, 0)) #+ 
 # coord_cartesian(ylim = c(2, 3.75))
  
```
